name: Build

on: 
  push:
    branches:
      - main

jobs:
  avoid_reduncy:
    runs-on: ubuntu-22.04
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
          
  lint: 
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Install dependencies
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - run: yarn install --frozen-lockfile
    - run: yarn lint

  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install dependencies
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - run: yarn install --frozen-lockfile
    - name: Build application web extension
      run: yarn build:ext
    # - uses: actions/upload-artifact@v3
    #   with:
    #     name: web-extension
    #     path: packages/web-extension/dist

  test:
    needs: [lint, build]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: yarn install --frozen-lockfile
      # - name: Download artifact
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: web-extension
      #     path: build/
      - name: Test
        run: yarn test